//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxPropertyGrid.Samples.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxPropertyGrid.Samples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Localization Example.
        /// </summary>
        public static string LocaledPropGroupName {
            get {
                return ResourceManager.GetString("LocaledPropGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Boolean Property.
        /// </summary>
        public static string LocaledBoolPropName {
            get {
                return ResourceManager.GetString("LocaledBoolPropName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a help text for the boolean property..
        /// </summary>
        public static string LocaledBoolPropHelp {
            get {
                return ResourceManager.GetString("LocaledBoolPropHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String Property.
        /// </summary>
        public static string LocaledStringPropName {
            get {
                return ResourceManager.GetString("LocaledStringPropName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a help text for the string property..
        /// </summary>
        public static string LocaledStringPropHelp {
            get {
                return ResourceManager.GetString("LocaledStringPropHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double Property.
        /// </summary>
        public static string LocaledDoublePropName {
            get {
                return ResourceManager.GetString("LocaledDoublePropName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a help text for the double property..
        /// </summary>
        public static string LocaledDoublePropHelp {
            get {
                return ResourceManager.GetString("LocaledDoublePropHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enum Property.
        /// </summary>
        public static string LocaledEnumPropName {
            get {
                return ResourceManager.GetString("LocaledEnumPropName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a help text for the enum property..
        /// </summary>
        public static string LocaledEnumPropHelp {
            get {
                return ResourceManager.GetString("LocaledEnumPropHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color Property.
        /// </summary>
        public static string LocaledColorPropName {
            get {
                return ResourceManager.GetString("LocaledColorPropName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a help text for the color property..
        /// </summary>
        public static string LocaledColorPropHelp {
            get {
                return ResourceManager.GetString("LocaledColorPropHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date Property.
        /// </summary>
        public static string LocaledDatePropName {
            get {
                return ResourceManager.GetString("LocaledDatePropName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a help text for the date property..
        /// </summary>
        public static string LocaledDatePropHelp {
            get {
                return ResourceManager.GetString("LocaledDatePropHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Localed enum value.
        /// </summary>
        public static string LocaledEnumValueText {
            get {
                return ResourceManager.GetString("LocaledEnumValueText", resourceCulture);
            }
        }
    }
}
